version: '3.1'

services:
  database:
    image: mysql
    container_name: adonisjs-5-boilerplate
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'default'
    ports:
      - '3306:3306'
